apiVersion: v1
kind: Service
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  selector:
    app: python-flask-app
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5000
      nodePort: 31200
